# Generated by Django 4.2.11 on 2024-05-07 06:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeekDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ],
                        unique=True,
                        verbose_name="день недели",
                    ),
                ),
            ],
            options={
                "verbose_name": "день недели",
                "verbose_name_plural": "дни недели",
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=250, verbose_name="действие")),
                ("location", models.CharField(max_length=250, verbose_name="место")),
                ("time", models.TimeField(default="12:00", verbose_name="время")),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False, verbose_name="признак приятности"
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="награда"
                    ),
                ),
                (
                    "execution_time",
                    models.IntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="время на выполнение(сек)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="признак публичности"
                    ),
                ),
                (
                    "days",
                    models.ManyToManyField(
                        to="habits.weekday", verbose_name="дни(периодичность)"
                    ),
                ),
                (
                    "linked_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="связь",
                    ),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
            },
        ),
    ]
