# Generated by Django 4.2.11 on 2024-05-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(default="12:00:00", verbose_name="время"),
        ),
    ]
