# Generated by Django 4.2.11 on 2024-05-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="execution_time",
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name="время на выполнение(сек)"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="периодичность(дни)"
            ),
        ),
    ]
