# Generated by Django 4.2.11 on 2024-05-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_execution_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="is_publicity",
        ),
        migrations.AddField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                default=False, verbose_name="признак публичности"
            ),
        ),
    ]
