# Generated by Django 4.2.11 on 2024-05-06 04:49

from django.db import migrations, models
import habits.services


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_remove_habit_is_publicity_habit_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                default=habits.services.get_current_time, verbose_name="время"
            ),
        ),
    ]
